"""add lesson plan cols

Revision ID: 217433baa219
Revises: f2bace9d3d51
Create Date: 2026-03-03 21:56:15.476496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217433baa219'
down_revision: Union[str, Sequence[str], None] = 'f2bace9d3d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_projects', sa.Column('outline_json', sa.Text(), nullable=True))
    op.add_column('lesson_projects', sa.Column('resource_recommendations_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_projects', 'resource_recommendations_json')
    op.drop_column('lesson_projects', 'outline_json')
    # ### end Alembic commands ###
