"""add lesson thematic mapping

Revision ID: 22b445ea3c98
Revises: 3af02233737b
Create Date: 2026-03-03 22:24:37.804584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b445ea3c98'
down_revision: Union[str, Sequence[str], None] = '3af02233737b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_projects', sa.Column('thematic_mapping_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_projects', 'thematic_mapping_json')
    # ### end Alembic commands ###
