"""add lesson synthesis and assessment

Revision ID: 3af02233737b
Revises: 217433baa219
Create Date: 2026-03-03 22:09:38.047276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af02233737b'
down_revision: Union[str, Sequence[str], None] = '217433baa219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_projects', sa.Column('summary_json', sa.Text(), nullable=True))
    op.add_column('lesson_projects', sa.Column('assessments_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_projects', 'assessments_json')
    op.drop_column('lesson_projects', 'summary_json')
    # ### end Alembic commands ###
