"""make lesson

Revision ID: f2bace9d3d51
Revises: 3e99c69673d6
Create Date: 2026-03-03 16:59:58.170344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bace9d3d51'
down_revision: Union[str, Sequence[str], None] = '3e99c69673d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('instructional_focus', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('instructor_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_user_id'], ['users.id'], name=op.f('fk_lesson_projects_instructor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_projects'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_projects')
    # ### end Alembic commands ###
